spring.application.name=Hikey

# Spring Config
spring.config.import=optional:file:.env[.properties]

# Docker Compose
spring.docker.compose.lifecycle-management=start-only

# Spring Datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# JWT / Authentication
jwt.secret=${JWT_SECRET}

# JSON Settings
spring.jackson.property-naming-strategy=SNAKE_CASE